version: '2'

volumes:
    logs:
        driver: local

services:
    slim:
        image: php:7-alpine
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public public/index.php
        environment:
            docker: "true"
            DB_HOST: 'sgcg.db'
            DB_DATABASE: 'sgcg'
            DB_USERNAME: 'root'
            DB_PASSWORD: 'admin'
        ports:
            - 8080:8080
        volumes:
            - .:/var/www
            - logs:/var/www/logs
